/* 
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;
import com.mycompany.absensi.rfid.object.MongoManager;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author HP
 */
public class MainFrameMahasiswa extends javax.swing.JFrame {

    // Ini baris 13 yang benar, tanpa kata 'import' di tengahnya
    private static final Logger logger = Logger.getLogger(MainFrameMahasiswa.class.getName());

    public MainFrameMahasiswa() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
    mainContent.add(new PanelHome()); // Ganti contentPanel jadi mainContent
    mainContent.revalidate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        btnHome = new javax.swing.JButton();
        btnAbsensi = new javax.swing.JButton();
        btnReward = new javax.swing.JButton();
        btnProfile = new javax.swing.JButton();
        btnJadwal = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        btnKelolaSiswa = new javax.swing.JButton();
        btnMenuRiwayat = new javax.swing.JButton();
        mainContent = new javax.swing.JPanel();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));
        jPanel1.setPreferredSize(new java.awt.Dimension(250, 250));

        btnHome.setText("HOME");
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });

        btnAbsensi.setText("Absensi");
        btnAbsensi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAbsensiActionPerformed(evt);
            }
        });

        btnReward.setText("Reward");
        btnReward.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRewardActionPerformed(evt);
            }
        });

        btnProfile.setText("Profile");
        btnProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProfileActionPerformed(evt);
            }
        });

        btnJadwal.setText("Jadwal/ruangan");
        btnJadwal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJadwalActionPerformed(evt);
            }
        });

        btnLogout.setBackground(new java.awt.Color(255, 51, 51));
        btnLogout.setText("LOGOUT");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        btnKelolaSiswa.setText("Kelola Siswa");
        btnKelolaSiswa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKelolaSiswaActionPerformed(evt);
            }
        });

        btnMenuRiwayat.setText("Riwayat absensi");
        btnMenuRiwayat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuRiwayatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(btnHome, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(btnAbsensi, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(btnJadwal, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(btnReward, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(btnProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnKelolaSiswa, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                            .addComponent(btnMenuRiwayat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(50, 50, 50))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(btnHome, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80)
                .addComponent(btnAbsensi, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(btnJadwal, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(btnReward, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(btnProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(btnKelolaSiswa, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnMenuRiwayat, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.LINE_START);

        mainContent.setBackground(new java.awt.Color(204, 204, 255));
        mainContent.setLayout(new java.awt.BorderLayout());
        getContentPane().add(mainContent, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
mainContent.removeAll();
mainContent.add(new PanelHome(), java.awt.BorderLayout.CENTER);
mainContent.revalidate();
mainContent.repaint();
    }//GEN-LAST:event_btnHomeActionPerformed

    private void btnAbsensiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAbsensiActionPerformed
System.out.println("--- DEBUG: Tombol Absensi Diklik ---");
    
    // 1. Hapus semua komponen yang ada di mainContent
    mainContent.removeAll();
    
    // 2. Buat instance baru dari PanelAbsensi
    // Pastikan package 'gui' sudah sesuai dengan struktur folder Anda
    gui.PanelAbsensi absen = new gui.PanelAbsensi();
    
    // 3. Tambahkan ke mainContent
    // Menggunakan BorderLayout.CENTER adalah pilihan terbaik untuk UI yang responsif
    mainContent.add(absen, java.awt.BorderLayout.CENTER);
    
    // 4. Sinkronisasi ulang layout dan tampilan
    mainContent.revalidate();
    mainContent.repaint();
    
    System.out.println("--- DEBUG: Panel Absensi berhasil dimuat ke mainContent ---");
    }//GEN-LAST:event_btnAbsensiActionPerformed

    private void btnProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProfileActionPerformed
mainContent.removeAll();
    // Memanggil file PanelProfil yang sudah kamu desain
    mainContent.add(new PanelProfil(), java.awt.BorderLayout.CENTER); 
    mainContent.revalidate();
    mainContent.repaint();
    }//GEN-LAST:event_btnProfileActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
int jawab = JOptionPane.showConfirmDialog(null, "Yakin ingin Logout?", "Konfirmasi", JOptionPane.YES_NO_OPTION);

if (jawab == JOptionPane.YES_OPTION) {
    // Membuka kembali form login
    new LoginForm().setVisible(true); 
    
    // Menutup frame saat ini (MainFrameMahasiswa/Admin)
    this.dispose(); 
}        // TODO add your handling code here:
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnRewardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRewardActionPerformed
mainContent.removeAll();
mainContent.add(new PanelRewardProfile(), java.awt.BorderLayout.CENTER);
mainContent.revalidate();
mainContent.repaint();
    }//GEN-LAST:event_btnRewardActionPerformed

    private void btnJadwalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJadwalActionPerformed
// Menghapus panel lama yang ada di sebelah kanan
    mainContent.removeAll();
    
    // Memanggil PanelKelolaJadwal yang baru saja kita buat (image_850442.png)
    PanelKelolaJadwal pJadwal = new PanelKelolaJadwal();
    
    // Menaruh panel jadwal ke dalam area konten utama
    mainContent.add(pJadwal);
    
    // Refresh tampilan agar muncul seketika
    mainContent.repaint();
    mainContent.revalidate();
    
    System.out.println("--- DEBUG: Panel Kelola Jadwal berhasil dimuat ke mainContent ---");
    }//GEN-LAST:event_btnJadwalActionPerformed

    private void btnKelolaSiswaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKelolaSiswaActionPerformed
// 1. Bersihkan konten yang ada di panel utama (mainContent)
    mainContent.removeAll();
    
    // 2. Tambahkan PanelKelolaSiswa ke dalam mainContent
    // Pastikan nama class-nya sudah benar sesuai file yang kamu buat
    mainContent.add(new PanelKelolaSiswa());
    
    // 3. Refresh tampilan agar panel muncul
    mainContent.repaint();
    mainContent.revalidate();
    
    // Debugging (opsional) untuk memastikan tombol bekerja
    System.out.println("--- DEBUG: Panel Kelola Siswa berhasil dimuat ke mainContent ---");

    }//GEN-LAST:event_btnKelolaSiswaActionPerformed

    private void btnMenuRiwayatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuRiwayatActionPerformed
try {
        // 1. Buat objek baru dari file PanelRiwayatAbsensi kamu
        gui.PanelRiwayatAbsensi panelRiwayat = new gui.PanelRiwayatAbsensi();
        
        // 2. Ambil koneksi database dan koleksi 'Absensilog' dari MongoDB
        // (Sesuaikan 'MongoManager' dengan kelas pengelola databasemu)
        var database = MongoManager.getDatabase(); 
        var koleksiAbsen = database.getCollection("Absensilog");
        
        // 3. Perintahkan panel riwayat untuk menarik data terbaru
        panelRiwayat.loadDariDatabase(koleksiAbsen);
        
        // 4. Bersihkan mainContent dan masukkan panel riwayat yang baru di-load
        mainContent.removeAll();
        mainContent.add(panelRiwayat);
        mainContent.repaint();
        mainContent.revalidate();
        
        System.out.println("--- DEBUG: Panel Riwayat Absensi berhasil dimuat ke mainContent ---");
        
    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Gagal memuat data riwayat: " + e.getMessage());
    }

    }//GEN-LAST:event_btnMenuRiwayatActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MainFrameMahasiswa().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAbsensi;
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnJadwal;
    private javax.swing.JButton btnKelolaSiswa;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnMenuRiwayat;
    private javax.swing.JButton btnProfile;
    private javax.swing.JButton btnReward;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel mainContent;
    // End of variables declaration//GEN-END:variables
}
