/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui;

import com.mycompany.absensi.rfid.object.GenericDAO;
import com.mycompany.absensi.rfid.object.LogAbsensi; // Pastikan ini mengarah ke folder .object
import javax.swing.JPanel;
import java.util.List;
/**
 *
 * @author HP
 */
public class PanelAbsensi extends javax.swing.JPanel {

    
GenericDAO<LogAbsensi> dao = new GenericDAO<>("log_absensi", LogAbsensi.class);

// Fungsi untuk mencetak kartu oren
public javax.swing.JPanel buatKartu(String nama, String id) {
    // Membuat panel baru dengan layout 2 baris (Nama & ID)
    javax.swing.JPanel p = new javax.swing.JPanel(new java.awt.GridLayout(2, 1, 5, 5));
    
    // Setting warna Luxury (Oranye Kecokelatan) & Ukuran
    p.setBackground(new java.awt.Color(210, 140, 80)); 
    p.setPreferredSize(new java.awt.Dimension(150, 80));
    p.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));

    // Label Nama Siswa
    javax.swing.JLabel l1 = new javax.swing.JLabel(nama);
    l1.setForeground(java.awt.Color.WHITE);
    l1.setFont(new java.awt.Font("SansSerif", java.awt.Font.BOLD, 14));

    // Label ID Siswa
    javax.swing.JLabel l2 = new javax.swing.JLabel("ID: " + id);
    l2.setForeground(new java.awt.Color(240, 240, 240));
    l2.setFont(new java.awt.Font("SansSerif", java.awt.Font.PLAIN, 11));

    p.add(l1);
    p.add(l2);

    return p;
}
public void refreshData() {
    panelKontainer.removeAll(); 
    List<LogAbsensi> list = dao.findAll(); 
    for (LogAbsensi d : list) {
        panelKontainer.add(buatKartu(d.getUidRfid(), d.getStatus())); 
    }
    panelKontainer.revalidate();
    panelKontainer.repaint();
} // Baris ini harus ada kurung tutupnya!

public PanelAbsensi() {
    initComponents();
    refreshData();
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelTombol = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        panelKontainer = new javax.swing.JPanel();

        setLayout(new java.awt.BorderLayout());

        jButton1.setBackground(new java.awt.Color(255, 51, 51));
        jButton1.setText("Save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(153, 255, 153));
        jButton2.setText("Refresh");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(153, 153, 255));
        jButton3.setText("Delete");

        jButton4.setBackground(new java.awt.Color(204, 204, 0));
        jButton4.setText("Edit");

        panelKontainer.setBackground(new java.awt.Color(255, 153, 102));
        panelKontainer.setPreferredSize(new java.awt.Dimension(1000, 800));
        panelKontainer.setLayout(new java.awt.GridLayout(0, 3, 10, 10));
        jScrollPane1.setViewportView(panelKontainer);

        javax.swing.GroupLayout panelTombolLayout = new javax.swing.GroupLayout(panelTombol);
        panelTombol.setLayout(panelTombolLayout);
        panelTombolLayout.setHorizontalGroup(
            panelTombolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTombolLayout.createSequentialGroup()
                .addGap(213, 213, 213)
                .addComponent(jButton1)
                .addGap(5, 5, 5)
                .addComponent(jButton2)
                .addGap(5, 5, 5)
                .addComponent(jButton3)
                .addGap(5, 5, 5)
                .addComponent(jButton4)
                .addGap(253, 253, 253))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTombolLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 763, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelTombolLayout.setVerticalGroup(
            panelTombolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTombolLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(panelTombolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addGap(52, 52, 52)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(81, Short.MAX_VALUE))
        );

        add(panelTombol, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        refreshData();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        refreshData();
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panelKontainer;
    private javax.swing.JPanel panelTombol;
    // End of variables declaration//GEN-END:variables
}
