/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui;

/**
 *
 * @author HP
 */
public class PanelKelolaSiswa extends javax.swing.JPanel {

    /**
     * Creates new form PanelKelolaSiswa
     */
    public PanelKelolaSiswa() {
        initComponents();   // Bawaan NetBeans untuk load design
        loadDataKeGrid();         
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        panelKoleksi = new javax.swing.JPanel();
        panelGridKartu = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        txtNama = new javax.swing.JTextField();
        txtKelas = new javax.swing.JTextField();
        txtAlamat = new javax.swing.JTextField();
        txtRfid = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnCari = new javax.swing.JButton();
        txtSearch = new javax.swing.JTextField();

        jPanel2.setBackground(new java.awt.Color(155, 235, 215));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jScrollPane1.setBackground(new java.awt.Color(204, 255, 204));
        jScrollPane1.setMinimumSize(new java.awt.Dimension(40, 40));
        jScrollPane1.setPreferredSize(new java.awt.Dimension(700, 400));

        panelKoleksi.setBackground(new java.awt.Color(204, 204, 255));
        panelKoleksi.setLayout(new java.awt.GridLayout(0, 3, 2, 2));
        jScrollPane1.setViewportView(panelKoleksi);

        panelGridKartu.setBackground(new java.awt.Color(255, 255, 255));
        panelGridKartu.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jPanel3.setBackground(new java.awt.Color(226, 232, 240));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("DATA SISWA");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(106, 106, 106))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel5)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jButton1.setBackground(new java.awt.Color(204, 255, 204));
        jButton1.setText("SIMPAN");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        txtNama.setBackground(new java.awt.Color(204, 204, 204));
        txtNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNamaActionPerformed(evt);
            }
        });

        txtKelas.setBackground(new java.awt.Color(204, 204, 204));

        txtAlamat.setBackground(new java.awt.Color(204, 204, 204));
        txtAlamat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAlamatActionPerformed(evt);
            }
        });

        txtRfid.setBackground(new java.awt.Color(204, 204, 204));
        txtRfid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRfidActionPerformed(evt);
            }
        });

        jLabel2.setText("KELAS");

        jLabel3.setText("ALAMAT");

        jLabel4.setText("RFID");

        jLabel1.setText("NAMA");

        javax.swing.GroupLayout panelGridKartuLayout = new javax.swing.GroupLayout(panelGridKartu);
        panelGridKartu.setLayout(panelGridKartuLayout);
        panelGridKartuLayout.setHorizontalGroup(
            panelGridKartuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGridKartuLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(panelGridKartuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelGridKartuLayout.createSequentialGroup()
                        .addGroup(panelGridKartuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(panelGridKartuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtKelas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtRfid, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelGridKartuLayout.createSequentialGroup()
                        .addGroup(panelGridKartuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3))
                        .addGroup(panelGridKartuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelGridKartuLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                                .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(1, 1, 1))
                            .addGroup(panelGridKartuLayout.createSequentialGroup()
                                .addGap(18, 46, Short.MAX_VALUE)
                                .addComponent(txtAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelGridKartuLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );
        panelGridKartuLayout.setVerticalGroup(
            panelGridKartuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGridKartuLayout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(panelGridKartuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(panelGridKartuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(panelGridKartuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtKelas, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(panelGridKartuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtRfid, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63))
        );

        btnCari.setBackground(new java.awt.Color(204, 255, 153));
        btnCari.setText("Cari");
        btnCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariActionPerformed(evt);
            }
        });

        txtSearch.setToolTipText("contoh : riski");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelGridKartu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 915, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCari)
                .addGap(333, 333, 333))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCari, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelGridKartu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 594, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(418, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
try {
            // 1. Ambil data dari input form kiri
            String nama = txtNama.getText().trim();
            String kelas = txtKelas.getText().trim();
            String alamat = txtAlamat.getText().trim();
            String rfid = txtRfid.getText().trim();

            // Validasi input wajib diisi
            if (nama.isEmpty() || kelas.isEmpty() || alamat.isEmpty() || rfid.isEmpty()) {
                javax.swing.JOptionPane.showMessageDialog(this, "Semua data form wajib diisi!");
                return;
            }

            // 2. Hubungkan ke koleksi 'siswa' di MongoDB
            com.mongodb.client.MongoCollection<org.bson.Document> col = 
                com.mycompany.absensi.rfid.object.MongoManager.getCollectionsiswa();

            if (col != null) {
                
                // =======================================================================
                // PERIKSA: Apakah form ini sedang dalam mode EDIT atau mode INPUT BARU?
                // =======================================================================
                if (txtRfid.isEditable() == false) {
                    // A. JIKA RFID TIDAK BISA DIEDIT -> BERARTI LAGI MODE EDIT DATA LAMA!
                    org.bson.Document queryCari = new org.bson.Document("uidRfid", rfid);
                    
                    org.bson.Document dataBaru = new org.bson.Document()
                            .append("namalengkap", nama) // Sesuaikan key huruf kecil di MongoDB Compass
                            .append("departemen", kelas)
                            .append("alamat", alamat);
                    
                    org.bson.Document updateOperator = new org.bson.Document("$set", dataBaru);
                    
                    // Eksekusi Update Permanen
                    col.updateOne(queryCari, updateOperator);
                    javax.swing.JOptionPane.showMessageDialog(this, "Perubahan data " + nama + " berhasil disimpan permanen!");
                    
                    // Buka kembali kunci kolom RFID agar bisa input data baru lagi nanti
                    txtRfid.setEditable(true);
                    
                } else {
                    // B. JIKA RFID MASIH BISA DIEDIT -> BERARTI INPUT DATA BARU!
                    // Cek dulu ke database, apakah nomor RFID ini sudah terdaftar sebelumnya?
                    org.bson.Document cekRfid = col.find(new org.bson.Document("uidRfid", rfid)).first();
                    if (cekRfid != null) {
                        javax.swing.JOptionPane.showMessageDialog(this, "Gagal! Nomor RFID ini sudah terdaftar atas nama: " + cekRfid.getString("namalengkap"));
                        return;
                    }
                    
                    // Jika belum ada, lakukan insert data baru
                    org.bson.Document docBaru = new org.bson.Document("namalengkap", nama)
                            .append("departemen", kelas)
                            .append("alamat", alamat)
                            .append("uidRfid", rfid);
                    
                    col.insertOne(docBaru);
                    javax.swing.JOptionPane.showMessageDialog(this, "Data siswa baru berhasil ditambahkan!");
                }

                // 3. Bersihkan kembali isi form input setelah simpan/edit selesai
                txtNama.setText("");
                txtKelas.setText("");
                txtAlamat.setText("");
                txtRfid.setText("");

                // 4. REFRESH GRID UTAMA biar kartu-kartunya langsung ter-update seketika
                loadDataKeGrid();
            }
        } catch (Exception e) {
            System.err.println("Error pada Tombol Simpan: " + e.getMessage());
            javax.swing.JOptionPane.showMessageDialog(this, "Terjadi kesalahan sistem: " + e.getMessage());
        }
    }
        public void loadDataKeGrid() {
       // 1. Bersihkan panel abu-abu agar data tidak menumpuk saat di-refresh
        panelKoleksi.removeAll(); 

        try {
            // 2. Panggil langsung lewat Class karena method-nya static
            com.mongodb.client.MongoCollection<org.bson.Document> col = com.mycompany.absensi.rfid.object.MongoManager.getCollectionsiswa();

            if (col != null) {
                // 3. Looping mengambil data dari MongoDB
                for (org.bson.Document doc : col.find()) {
                    // Panggil template kartu kecil yang sudah kamu buat
                    ItemSiswa item = new ItemSiswa();

                    // AMBIL KEYS SESUAI COMPASS (menggunakan huruf kecil semua/sesuai DB)
                    String nama = doc.getString("namalengkap") != null ? doc.getString("namalengkap") : "-";
                    String kelas = doc.getString("departemen") != null ? doc.getString("departemen") : "-";
                    String alamat = doc.getString("alamat") != null ? doc.getString("alamat") : "-";
                    String rfid = doc.getString("uidRfid") != null ? doc.getString("uidRfid") : "-";

                    // 4. Set teks ke label template kartu kamu
                    // SEPERTI INI FORMAT TERBARUNYA:
item.lblNama.setText("<html><b>Nama:</b> " + nama + "</html>");
item.lblDepartemen.setText("<html><b>Kelas:</b> " + kelas + "</html>");
item.lblAlamat.setText("<html><b>Alamat:</b> " + alamat + "</html>");
item.lblRfid.setText("<html><b>RFID:</b> " + rfid + "</html>");

                    // =========================================================
                    // 5. FUNGSI TOMBOL EDIT (Ketik data kartu ke form input utama)
                    // =========================================================
item.btnEdit.addActionListener(new java.awt.event.ActionListener() {
    @Override
    public void actionPerformed(java.awt.event.ActionEvent evt) {
        // 1. Melempar data asli kartu ke JTextField form kiri
        txtNama.setText(nama);
        txtKelas.setText(kelas);
        txtAlamat.setText(alamat);
        txtRfid.setText(rfid);

        // 2. WAJIB DISET TRUE: Supaya field nama, kelas, dan alamat BISA diketik/diedit ulang
        txtNama.setEditable(true);
        txtKelas.setEditable(true);
        txtAlamat.setEditable(true);
        
        // 3. WAJIB DISET FALSE: Hanya RFID yang dikunci agar tidak bisa diubah-ubah nilainya
        txtRfid.setEditable(false); 
        
        System.out.println("Memilih data siswa: " + nama + " untuk diedit.");
    }
});

// =========================================================================
// 2. TOMBOL SIMPAN EDIT BARU (Untuk menyimpan hasil perubahan form ke DB)
// =========================================================================
item.btnSimpanEdit.addActionListener(new java.awt.event.ActionListener() {
    @Override
    public void actionPerformed(java.awt.event.ActionEvent evt) {
        try {
            // Ambil teks terbaru yang sedang diketik user di form kiri
            String namaBaru = txtNama.getText().trim();
            String kelasBaru = txtKelas.getText().trim();
            String alamatBaru = txtAlamat.getText().trim();
            
            if (namaBaru.isEmpty() || kelasBaru.isEmpty() || alamatBaru.isEmpty()) {
                javax.swing.JOptionPane.showMessageDialog(null, "Form input di kiri tidak boleh kosong saat menyimpan edit!");
                return;
            }
            
            // Lakukan update ke MongoDB berdasarkan rfid asli milik kartu ini
            org.bson.Document queryCari = new org.bson.Document("uidRfid", rfid);
            
            org.bson.Document dataTerupdate = new org.bson.Document()
                    .append("namalengkap", namaBaru)
                    .append("departemen", kelasBaru)
                    .append("alamat", alamatBaru);
            
            org.bson.Document updateOperator = new org.bson.Document("$set", dataTerupdate);
            
            col.updateOne(queryCari, updateOperator);
            javax.swing.JOptionPane.showMessageDialog(null, "Perubahan data " + namaBaru + " berhasil disimpan ke database!");
            
            // Kembalikan form ke mode normal
            txtRfid.setEditable(true);
            txtNama.setText("");
            txtKelas.setText("");
            txtAlamat.setText("");
            txtRfid.setText("");
            
            // Refresh Grid agar kartu langsung menampilkan nama yang baru
            loadDataKeGrid();
            
        } catch (Exception e) {
            System.err.println("Gagal simpan edit: " + e.getMessage());
        }
    }
                    });

                    // =========================================================
                    // 6. FUNGSI TOMBOL HAPUS (Langsung hapus dari MongoDB)
                    // =========================================================
                    item.btnHapus.addActionListener(new java.awt.event.ActionListener() {
                        @Override
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                            int konfirmasi = javax.swing.JOptionPane.showConfirmDialog(
                                null, 
                                "Apakah Anda yakin ingin menghapus data " + nama + "?", 
                                "Konfirmasi Hapus", 
                                javax.swing.JOptionPane.YES_NO_OPTION
                            );

                            if (konfirmasi == javax.swing.JOptionPane.YES_OPTION) {
                                // Hapus dari database berdasarkan UID RFID yang unik
                                org.bson.Document queryHapus = new org.bson.Document("uidRfid", rfid);
                                col.deleteOne(queryHapus);

                                javax.swing.JOptionPane.showMessageDialog(null, "Data " + nama + " berhasil dihapus!");

                                // Refresh tampilan grid secara otomatis setelah menghapus
                                loadDataKeGrid();
                            }
                        }
                    });
                    // =========================================================

                    // Masukkan kartu ke panel grid utama
                    panelKoleksi.add(item);
                }
            }
        } catch (Exception e) {
            System.out.println("Gagal memuat data ke Grid: " + e.getMessage());
        }

        // 7. Gambar ulang komponen Swing agar langsung muncul di layar
        panelKoleksi.revalidate();
        panelKoleksi.repaint();
    
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamaActionPerformed

    private void txtAlamatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAlamatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAlamatActionPerformed

    private void txtRfidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRfidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRfidActionPerformed

    private void btnCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariActionPerformed
        cariDataSiswa();
    }//GEN-LAST:event_btnCariActionPerformed
private void cariDataSiswa() {
    // 1. Ambil teks dari kolom pencarian, hapus spasi, dan jadikan huruf kecil
    String keyword = txtSearch.getText().trim().toLowerCase();
    
    // 2. Kosongkan panelKoleksi (tempat kartu berada) agar data lama tidak menumpuk
    panelKoleksi.removeAll(); 
    
    try {
        // 3. Ambil koneksi database MongoDB langsung lewat MongoManager bawaanmu
        com.mongodb.client.MongoCollection<org.bson.Document> col = 
            com.mycompany.absensi.rfid.object.MongoManager.getCollectionsiswa();

        if (col != null) {
            // 4. Lakukan looping data dari MongoDB
            for (org.bson.Document doc : col.find()) {
                
                // Ambil data string dari document database
                String nama = doc.getString("namalengkap") != null ? doc.getString("namalengkap") : "-";
                String kelas = doc.getString("departemen") != null ? doc.getString("departemen") : "-";
                String alamat = doc.getString("alamat") != null ? doc.getString("alamat") : "-";
                String rfid = doc.getString("uidRfid") != null ? doc.getString("uidRfid") : "-";

                // 5. Jalankan Filter logika pencarian
                if (keyword.isEmpty() || 
                    nama.toLowerCase().contains(keyword) || 
                    rfid.contains(keyword) ||
                    alamat.toLowerCase().contains(keyword)) {
                    
                    // Jika cocok dengan keyword, buat objek kartu barunya
                    ItemSiswa item = new ItemSiswa();

                    // Set teks label kartu persis seperti fungsi load data kamu
                    item.lblNama.setText("<html><b>Nama:</b> " + nama + "</html>");
                    item.lblDepartemen.setText("<html><b>Kelas:</b> " + kelas + "</html>");
                    item.lblAlamat.setText("<html><b>Alamat:</b> " + alamat + "</html>");
                    item.lblRfid.setText("<html><b>RFID:</b> " + rfid + "</html>");

                    // Pasang fungsi tombol Edit, Simpan Edit, dan Hapus agar kartu hasil pencarian tetap bisa diklik
                    item.btnEdit.addActionListener(new java.awt.event.ActionListener() {
                        @Override
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                            txtNama.setText(nama);
                            txtKelas.setText(kelas);
                            txtAlamat.setText(alamat);
                            txtRfid.setText(rfid);
                            txtNama.setEditable(true);
                            txtKelas.setEditable(true);
                            txtAlamat.setEditable(true);
                            txtRfid.setEditable(false); 
                        }
                    });

                    item.btnSimpanEdit.addActionListener(new java.awt.event.ActionListener() {
                        @Override
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                            try {
                                String namaBaru = txtNama.getText().trim();
                                String kelasBaru = txtKelas.getText().trim();
                                String alamatBaru = txtAlamat.getText().trim();
                                
                                if (namaBaru.isEmpty() || kelasBaru.isEmpty() || alamatBaru.isEmpty()) {
                                    javax.swing.JOptionPane.showMessageDialog(null, "Form input di kiri tidak boleh kosong saat menyimpan edit!");
                                    return;
                                }
                                
                                org.bson.Document queryCari = new org.bson.Document("uidRfid", rfid);
                                org.bson.Document dataTerupdate = new org.bson.Document()
                                        .append("namalengkap", namaBaru)
                                        .append("departemen", kelasBaru)
                                        .append("alamat", alamatBaru);
                                
                                col.updateOne(queryCari, new org.bson.Document("$set", dataTerupdate));
                                javax.swing.JOptionPane.showMessageDialog(null, "Perubahan data " + namaBaru + " berhasil disimpan!");
                                
                                txtRfid.setEditable(true);
                                txtNama.setText(""); txtKelas.setText(""); txtAlamat.setText(""); txtRfid.setText("");
                                cariDataSiswa(); // Refresh hasil pencarian
                            } catch (Exception e) {
                                System.err.println("Gagal simpan edit: " + e.getMessage());
                            }
                        }
                    });

                    item.btnHapus.addActionListener(new java.awt.event.ActionListener() {
                        @Override
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                            int konfirmasi = javax.swing.JOptionPane.showConfirmDialog(null, 
                                    "Apakah Anda yakin ingin menghapus data " + nama + "?", "Konfirmasi Hapus", javax.swing.JOptionPane.YES_NO_OPTION);
                            if (konfirmasi == javax.swing.JOptionPane.YES_OPTION) {
                                col.deleteOne(new org.bson.Document("uidRfid", rfid));
                                javax.swing.JOptionPane.showMessageDialog(null, "Data " + nama + " berhasil dihapus!");
                                cariDataSiswa(); // Refresh hasil pencarian
                            }
                        }
                    });

                    // Masukkan kartu yang lolos filter ke panelKoleksi
                    panelKoleksi.add(item);
                }
            }
        }
    } catch (Exception e) {
        System.out.println("Gagal menyaring data: " + e.getMessage());
    }

    // 6. Gambar ulang komponen panelKoleksi biar langsung berubah di layar monitor
    panelKoleksi.revalidate();
    panelKoleksi.repaint();
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCari;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panelGridKartu;
    private javax.swing.JPanel panelKoleksi;
    private javax.swing.JTextField txtAlamat;
    private javax.swing.JTextField txtKelas;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtRfid;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables

    private void showData(String text) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
